# Generated by Django 5.0 on 2023-12-27 09:14

import lmsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('Staff_image', models.ImageField(blank=True, null=True, upload_to=lmsapp.models.getFileName)),
                ('Staff_Name', models.CharField(max_length=150)),
                ('Staff_User_Name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('Staff_Identity_Number', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('Staff_NIC_Number', models.CharField(max_length=150)),
                ('Staff_Phone_Number', models.CharField(max_length=150)),
                ('Staff_Password', models.CharField(max_length=100)),
            ],
        ),
    ]
