# Generated by Django 5.0 on 2023-12-27 09:25

import lmsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_image', models.ImageField(blank=True, null=True, upload_to=lmsapp.models.getFileName)),
                ('Student_Name', models.CharField(max_length=150)),
                ('Student_User_Name', models.CharField(max_length=150)),
                ('Student_email', models.EmailField(max_length=50, unique=True)),
                ('Student_Registration_Number', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('Student_Admission_Number', models.CharField(max_length=150)),
                ('Student_NIC_Number', models.CharField(max_length=150)),
                ('Student_Phone_Number', models.CharField(max_length=150)),
                ('Student_Password', models.CharField(max_length=100)),
            ],
        ),
    ]
