# Generated by Django 5.0 on 2023-12-27 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Registered_Courses', models.CharField(choices=[('CS', 'Computer Science'), ('M', 'Maths'), ('B', 'Biology'), ('P', 'Physics')], max_length=128)),
                ('Student_date_of_birth', models.DateTimeField()),
                ('Department', models.CharField(choices=[('PY', 'Physical Science'), ('BS', 'biological Science'), ('ICT', 'Information Communication Technology'), ('HPT', 'Health Promotion')], max_length=128)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.student')),
            ],
        ),
    ]
